server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: CafeManagement
          uri: http://localhost:8082
          predicates:
            - Path=/orderManagements/**, 
        - id: Payment
          uri: http://localhost:8083
          predicates:
            - Path=/pays/**, 
        - id: CustomerManagement
          uri: http://localhost:8084
          predicates:
            - Path=/pushMessages/**, 
        - id: DashBoard
          uri: http://localhost:8085
          predicates:
            - Path=, /orderInfos/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: CafeManagement
          uri: http://cafeManagement:8080
          predicates:
            - Path=/orderManagements/**, 
        - id: Payment
          uri: http://payment:8080
          predicates:
            - Path=/pays/**, 
        - id: CustomerManagement
          uri: http://customerManagement:8080
          predicates:
            - Path=/pushMessages/**, 
        - id: DashBoard
          uri: http://dashBoard:8080
          predicates:
            - Path=, /orderInfos/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
